### ISSUE TITLE
Custom Ring All-Reduce between GPU0 and and GPU 7 is not compiled

### ISSUE THREAD

**Issue by rashidi1saeed** [microsoft/msccl#52]
Hi, I have a dgx-1 like system and I want to write a custom collective algorithm that performs All-Reduce between 2 GPUs (GPU0 and GPU7) using the NVLinks. My collective is as follows:

`
def allreduce_ring(size, instances, channels, protocol):
    topology = fully_connected(size)
    collective = AllReduce(size, size, True)
    ring_order = [0, 3, 2, 1, 5, 6, 4, 7]
    with MSCCLProgram(f"allreduce_ring_{channels}channelsperring", topology, collective, instances,
         protocol=protocol, threadblock_policy=ThreadblockPolicy.manual):

        # Reduce ring
        for step in range(0, size-1):
            for index in range(0, size):
                rank = 0
                next_rank = 0
                if index<4:
                    rank = (0 + step) % size
                    next_rank = (0 + step + 1) % size
                else:
                    rank = (7 - step) % size
                    next_rank = (7 - step - 1) % size
                rank = ring_order[rank]
                next_rank = ring_order [next_rank]
                channel = index%channels
                if step == size-2:
                    c = chunk(next_rank, Buffer.input, index)
                    c.reduce(chunk(rank, Buffer.input, index), ch=channel, recvtb=channel, sendtb=channel)
                else:
                    c = chunk(rank, Buffer.input, index)
                    c = c.copy(next_rank, Buffer.input, index, ch=channel, recvtb=channel, sendtb=channel)

        # Propagate ring
        for step in range(0, size-1):
            for index in range(0, size):
                rank = 0
                next_rank = 0
                if index>=4:
                    rank = (0 + step) % size
                    next_rank = (0 + step + 1) % size
                else:
                    rank = (7 - step) % size
                    next_rank = (7 - step - 1) % size
                rank = ring_order[rank]
                next_rank = ring_order [next_rank]
                channel = index%channels
                c = chunk(rank, Buffer.input, index)
                c = c.copy(next_rank, Buffer.input, index, ch=channel, recvtb=channel, sendtb=channel)
               
        XML()
parser = argparse.ArgumentParser()
parser.add_argument('--num_gpus', type=int, help ='number of gpus')
parser.add_argument('--channels', type=int, help='Number of channels to use for 1 instance of the ring [1-8]')
parser.add_argument('--instances', type=int, help='number of instances')
parser.add_argument('--protocol', type=str, default='LL128', choices=['Simple', 'LL', 'LL128'], help ='NCCL protocol. Default: LL128')
args = parser.parse_args()

allreduce_ring(args.num_gpus, args.instances, args.channels, args.protocol)
`

However, when trying to compile it and generate the xml, I get the following error:

`Traceback (most recent call last):
  File "/home/rashidi/msccl-tools/examples/mscclang/allreduce_a100_ring_0_7.py", line 67, in <module>
    allreduce_ring(args.num_gpus, args.instances, args.channels, args.protocol)
  File "/home/rashidi/msccl-tools/examples/mscclang/allreduce_a100_ring_0_7.py", line 57, in allreduce_ring
    XML()
  File "/home/rashidi/.local/lib/python3.10/site-packages/msccl/language/__init__.py", line 153, in XML
    print(_curr().generate_xml())
  File "/home/rashidi/.local/lib/python3.10/site-packages/msccl/language/__init__.py", line 129, in generate_xml
    return ir_to_xml(self.lower(), dependence_nop=self.dependence_nop)
  File "/home/rashidi/.local/lib/python3.10/site-packages/msccl/language/__init__.py", line 116, in lower
    manual_assign_tbs(self.instr_dag)
  File "/home/rashidi/.local/lib/python3.10/site-packages/msccl/language/tb_assignment.py", line 39, in manual_assign_tbs
    raise Exception(f"Illegal threadblock assignment. Trying to add {op} to threadblock {tbid}\n" \
Exception: Illegal threadblock assignment. Trying to add Op(rcs, 5, Ref(Buffer:i, Index:0, Size:1, Rank:1), Ref(Buffer:i, Index:0, Size:1, Rank:6), step:-1, tb:0) to threadblock 0
Threadblock 0 send:1 recv:6 channel:0
Operation send:6 recv:6 channel:0
`
I really appreciate if you have any solution to this!

**Comment by rashidi1saeed** [comment]
OK I was able to solve it using auto threadblock assignment!
